### ISSUE TITLE
Fix Reduction of Efficency with multiple cores

### ISSUE THREAD

**Issue by Bibby0110** [TheGamerdk/Server-Manager#1]
Code has been commented in CPU_local_manager

**Comment by sinraw7x** [comment]
Has this been fixed?

**Comment by Bibby0110** [comment]
Has not been fixed yet, will probably take quite some time

**Comment by sinraw7x** [comment]
Sure, i will add the needs fix label

**Comment by sinraw7x** [comment]
Ok, i will try to fix it

**Comment by sinraw7x** [comment]
This will end up on a recode of the entire cpu local manager, closing the issue
