### ISSUE TITLE
overlaying

### ISSUE THREAD

**Issue by sinraw7x** [TheGamerdk/Server-Manager#3]
On certain resolutions, some objects overlay others

**Comment by Bibby0110** [comment]
Do note this will be done late, due to the fact it has to be redone everytime a new object is added.

**Comment by sinraw7x** [comment]
Sure :+1:

**Comment by Bibby0110** [comment]
Closed in 0.0575 due to new usage of the canvas scaler component, tweaking is still needed. But that will be on the final UI design.
